" Environment {{{
	set nocompatible
	scriptencoding utf-8
	set encoding=utf-8
	set fileencodings=ucs-bom,utf-8,latin1
	set termencoding=utf-8
	" Directories {
		silent execute '!mkdir -p $HOME/.vimtmp/undo'
		set undodir=$HOME/.vimtmp/undo/
		set undofile

		set viminfo='50,n$HOME/.vimtmp/viminfo
	" }
"}}}

"Editing {{{
	set tabstop=3
	set shiftwidth=3
	set softtabstop=3
	set noexpandtab
	set autoindent

	set formatoptions-=t
	set cpoptions+=$

	set nowrap
	set nolinebreak
	set textwidth=79

	set pastetoggle=<F2>
	set clipboard=unnamed
" }}}
" Visuals {{{
	set title
	set wildmenu
	set wildmode=list:longest
	set cmdheight=2
	set showcmd
	set showmode
	set showmatch

	set splitright
	set splitbelow

	set incsearch
	set ignorecase
	set smartcase
	set invhlsearch

	set stl=%f\ %m\ %r%=Line:\ %l/%L[%p%%]\ Col:\ %c\ Buf:\ #%n\ [%b][0x%B]
	set laststatus=2

	if has("gui_running")
		set lbr wrap
		set guioptions-=m " no menu bar
		set guioptions-=T " no icon bar
	endif
	" Colors {
		if &term =~ "xterm"
			set t_Co=256
		endif

		syntax on
		set background=dark
		let g:molokai_original=1
		colorscheme molokai
	" }
" }}}
" Maps {{{
	iab #i #include
	iab #d #define
	iab dbg logger.message(LL_debug) <<

	nnoremap ; :set invhlsearch<CR>

	" do not loose selection after changing indentation
	vnoremap < <gv
	vnoremap > >gv

	nnoremap <S-Left> :tabprev<CR>
	nnoremap <S-Right> :tabnext<CR>
	vnoremap <S-Left> :tabprev<CR>
	vnoremap <S-Right> :tabnext<CR>
	inoremap <S-Left> <Esc>:tabprev<CR>
	inoremap <S-Right> <Esc>:tabnext<CR>

	nmap  ,n :set invhls<CR>:set hls<CR>
" }}}
" Autocmds {{{
	" cleanup spaces at line ends
	autocmd BufWritePre,FileWritePre * :%s/\s\s+$//e

	" add filetypes
	au BufNewFile,BufRead *.twig set filetype=jinja
" }}}
" vim:set foldmarker={{{,}}} foldlevel=2 foldmethod=marker:
